resource_types:
- name: webhook-notification
  type: docker-image
  source:
    repository: flavorjones/webhook-notification-resource

resources:
- name: gitter-channel # https://gitter.im/gitter-notifications-resource/community
  type: webhook-notification
  source:
    adapter: GitterActivityFeedAdapter
    url: ((webhook_url))
- name: discord-channel
  type: webhook-notification
  source:
    adapter: DiscordAdapter
    url: ((discord_test_url))

jobs:
- name: gitter-activity-feed
  plan:
  - put: gitter-channel
    params: { status: pending }
  - put: gitter-channel
    params: { status: started }
  - put: gitter-channel
    params: { status: failed }
  - put: gitter-channel
    params: { status: errored }
  - put: gitter-channel
    params: { status: aborted }
  - put: gitter-channel
    params: { status: xyzzy } # unknown
  - put: gitter-channel
    params: { status: succeeded }
- name: discord
  plan:
  - put: discord-channel
    params: { status: pending }
  - put: discord-channel
    params: { status: started }
  - put: discord-channel
    params: { status: failed }
  - put: discord-channel
    params: { status: errored }
  - put: discord-channel
    params: { status: aborted }
  - put: discord-channel
    params: { status: xyzzy } # unknown
  - put: discord-channel
    params: { status: succeeded }
